class BpmnConstants:
    SEQUENCE_FLOW = './/bpmn:sequenceFlow'
    USER_TASK = './/bpmn:userTask'
    EXCLUSIVE_GATEWAY = './/bpmn:exclusiveGateway'
    SERVICE_TASK = './/bpmn:serviceTask'
    END_EVENT = './/bpmn:endEvent'
    START_EVENT = './/bpmn:startEvent'
    TARGET_NODE = 'targetRef'
    SOURCE_NODE = 'sourceRef'
    CONDITION_EXPRESSION = './/bpmn:conditionExpression'
    PROCESS = './/bpmn:process'
